image_width: 1280
image_height: 800
camera_name: camera1
camera_matrix:
  rows: 3
  cols: 3
  data: [580.51137,   0.     , 622.56954,
           0.     , 581.54417, 398.92275,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.251102, 0.052554, 0.001455, 0.003036, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [424.0049 ,   0.     , 633.70593,   0.     ,
           0.     , 501.1473 , 400.90935,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
